nuance-communications/mix-cli

src/commands/entities/configure.ts, src/commands/entities/create.ts, src/mix/api/utils/entities-helpers.ts, src/utils/flags.ts, test/commands/entities/configure.test.ts, test/commands/entities/entities-test-data.ts
entities:configure had a number of issues:
- It was listing `undefined` instead of the entity name in the action message
- The entity-type flag was not required
- isA and hasA was treated as mandatory for type relational and they are not
- anaphora-type, no-canonicalize, data-type, dynamic and sensitive all had defaults which were ending up being used as update values in the body which went against the contract that properties not given explicit update values would be left unmodified.
=> fix: correct set of issues with entities:configure

src/commands/intents/create.ts, src/commands/intents/destroy.ts, src/commands/intents/get.ts, src/commands/intents/list.ts, src/commands/intents/rename.ts
Caught this during verification: the project flag needs to default to MIX_PROJECT if present.
=> fix: add MIX_PROJECT as default for project flag in all intents commands

src/commands/entities/create.ts, src/commands/entities/destroy.ts, src/commands/entities/get.ts, src/commands/entities/list.ts, src/commands/entities/rename.ts
As I was testing entities commands, I noted where cyan was missing from the output. I also added the project ID where it made sense.
=> fix: make consistent use of color in entities commands output

src/commands/entities/rename.ts, src/commands/intents/rename.ts, src/commands/projects/rename.ts, test/commands/entities/rename.test.ts, test/commands/intents/rename.test.ts, test/commands/projects/rename.test.ts
As discussed, aligning all rename commands to use `--new-name` instead of `--name`. The shortcut `-n` was also removed.
=> fix: change from --name to --new-name in rename commands

src/commands/entities/get.ts, src/utils/base/mix-command.ts
entities:get used to return the superset of key-value pairs. As a good number of keys don't apply to each entity type, that ended up creating a non-negligible number of lines with value "N/A". This was cluttering the output.
Only keys with defined values are now displayed in human-readable output. However, all keys were kept in the CSV output as to let users write a single parser.
=> fix: remove N/As from entities:get output

src/commands/entities/configure.ts, src/commands/entities/convert.ts, src/commands/entities/create.ts
I realized that it's easy to get "\\" swallowed by the command line if not quoted, which messes up pattern values for regular expressions. I added a warning and and fixed the relevant examples in entites:configure, entities:convert and entities:create.
=> fix: add warning regarding pattern values

src/commands/channels/create.ts, src/commands/channels/rename.ts, src/commands/projects/create.ts, src/utils/validations.ts
Handle empty/white space project names and channels
=> fix: Handle empty/white space project and channel names

src/commands/grammars/export.ts, test/commands/grammars/export.test.ts, test/commands/grammars/grammars-test-data.ts
Add unit test for grammars commands:
<b>grammars:export</b> - export the grammars for an entity
=> test: add grammars unit tests

CHANGELOG.md, README.md, src/utils/base/mix-command.ts
When running the jobs:get command with the --watch flag, mix-cli refreshes the token but does not pass it to the client, resulting on a 401 code returned by the endpoint. The refreshed token passed to the client to fix 401 error.
=> fix: refreshed token when watching job

src/commands/app-configs/get.ts
Fixed app-configs:get undefined options error while capturing options.
=> fix: app-configs-get undefined options error

.github/workflows/veracode.yaml
I have updated the set of files included in the zip sent to Veracode for scanning. I am excluding the node_modules directory as it puts unnecessary burden on Veracode and leads to long scan times. Veracode does recommend to exclude node_modules as well.
=> fix: exclude node_modules from zip packged for Veracode

src/commands/init.ts
This fixes [153](https://github.com/nuance-communications/mix-cli/issues/153)
=> chore: remove period after pathname in init output messages

src/commands/app-configs/deploy.ts, test/commands/app-configs/deploy.test.ts
This resolves [#155](https://github.com/nuance-communications/mix-cli/issues/155)
=> fix: add warning on redeploy instead of error

package-lock.json, package.json, test/help.test.ts
Resolves #171 
Have tested it out using the two tar files generated by `npm pack`. The one generated on `main` gives the TypeError. The one generated on this branch doesn't have that error.
=> fix: correct help for subcommands

src/utils/base/mix-command.ts
In its current implementation, mix-cli does not stop the "spinner" upon hitting an error with the backend. This leads to a situation where a full error message is given to the user (error message, error code and "try this") followed by a line that says something similar to "Retrieve projects for organization 99999... Done".
That last line is misleading. Explicitly stopping the spinner when the error happens will fix this.
This solves [#182](https://github.com/nuance-communications/mix-cli/issues/182).
=> fix: add failed message on error requests

README.md, src/commands/auth.ts, src/commands/init.ts, src/commands/system/list.ts, src/commands/system/version.ts, src/utils/base/base-command.ts, src/utils/base/mix-command.ts, src/utils/config.ts, src/utils/flags.ts, test/commands/env-configs/list.test.ts, test/help.test.ts, test/mocks.ts
This adds support for storing and switching between different configurations(referred to as "systems")
To use, run `mix init` as usual and enter the system name when it prompts you for the same. 
To switch, you can use `mix auth`. For example, to switch to `dev`, run
```
mix auth --system dev
```
=> feat: add support for multiple configs

CHANGELOG.md
Bringing the updated changelog from releasing back into beta to be in sync.
=> chore: merge main back to beta

.github/workflows/test.yml, package-lock.json, package.json, src/mix/client.ts, test/commands/grammars/replace.test.ts, test/commands/literals/import.test.ts, test/commands/ontology/import.test.ts, test/commands/projects/replace.test.ts, test/commands/samples/import.test.ts
This PR upgrades axios to 1.6.2 to address a vulnerability issue.
The type for headers had to be changed.
Node 16.x is removed from the test run in the pipeline and replaced with Node 20.x
The axios upgrade exposed a problem with a number of unit tests. It turns out that `createForm()` was not stubbed correctly. This is addressed and all unit tests pass.
Resolves #201
=> fix: upgrade axios to 1.6.2

package-lock.json, package.json
The security issue with follow-redirects is fixed by upgrading axios to 1.6.5
See https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6141137.
=> fix: address security issue with follow-redirects

README.md, package-lock.json, package.json, src/commands/auth.ts, src/commands/init.ts, src/commands/system/list.ts, src/mix/api/system.ts, src/mix/api/utils/build-url.ts, src/mix/client.ts, src/mix/types.ts, src/utils/base/base-command.ts, src/utils/base/mix-command.ts, src/utils/config.ts, src/utils/errors.ts, src/utils/msal-auth.ts, src/utils/msal-cache-plugin.ts, test/mocks.ts
This PR adds support for the device code authentication flow.
To add a system that uses device code authentication flow,
run the `init` command and answer `device` to the
"Authentication flow?" question.
Once a system is added using the `init` command, the other
commands can be used the same way they are used with systems
that support the client credentials grant flow.
=> feat: add experimental support for device code authentication flow

README.md, package-lock.json, package.json, src/commands/auth.ts, src/commands/init.ts, src/commands/system/list.ts, src/mix/api/system.ts, src/mix/api/utils/build-url.ts, src/mix/client.ts, src/mix/types.ts, src/utils/base/base-command.ts, src/utils/base/mix-command.ts, src/utils/config.ts, src/utils/errors.ts, src/utils/msal-auth.ts, src/utils/msal-cache-plugin.ts, test/mocks.ts
This PR adds support for the device code authentication flow.
To add a system that uses device code authentication flow,
run the init command and answer device to the
"Authentication flow?" question.
Once a system is added using the init command, the other
commands can be used the same way they are used with systems
that support the client credentials grant flow.
=> feat: merge beta to main

package-lock.json, package.json
The following packages needed to be upgraded to their most recent version:
- braces
- ejs
- micromatch
The follow-redirects package also needed to be upgraded to it most recent version and this was accomplished by upgrading axios.
=> fix: update axis (follow-redirects), braces, ejs and micromatch
