src/commands/auth.ts

fix: minor typo in commands/auth.ts success message

---

test/commands/builds/list.test.ts

chore: move hanging tests inside builds:list

---

src/commands/channels/deactivate.ts
src/mix/api/channels-types.ts
src/mix/api/channels.ts
test/commands/channels/channels-test-data.ts
test/commands/channels/deactivate.test.ts

feat: add channels:deactivate api adapter and command

---

src/commands/channels/activate.ts
src/mix/api/channels-types.ts
src/mix/api/channels.ts
test/commands/channels/activate.test.ts
test/commands/channels/channels-test-data.ts

feat: implement channels:activate api adapter and command

---

src/commands/channels/config.ts
src/commands/channels/configure.ts
src/mix/api/channels-types.ts
src/mix/api/channels.ts
src/utils/validations.ts
test/commands/channels/channels-test-data.ts
test/commands/channels/configure.test.ts

feat: implement channels:configure command

---

src/utils/flags.ts

fix: make --to-entity-type flag required in entities:convert

---

CHANGELOG.md

feat: bump version to 2.0.0

---

CHANGELOG.md

BREAKING CHANGE: bump to version 2.0.0

feat: bump to version 2.0.0

---

src/commands/app-configs/destroy.ts

Add color to output of the commands

fix: output color correction

---

src/commands/app-configs/get.ts
src/commands/app-configs/list.ts
src/commands/applications/list.ts
src/commands/builds/get.ts
src/commands/entities/get.ts
src/commands/environments/list.ts
src/commands/geographies/list.ts
src/commands/intents/get.ts
src/commands/intents/list.ts
src/commands/jobs/get.ts
src/commands/language-topics/list.ts
src/commands/organizations/list.ts
src/commands/projects/get.ts
src/commands/projects/list.ts

Add output message for commands that output empty tables.

fix: add not found treatment to get and list command output

---

src/commands/entity-types/list.ts
src/mix/api/ontology-types.ts
src/mix/api/ontology.ts

Added new command:
<b>entity-types:list</b> - list entity types

feat: add entity-types:list command

---

src/commands/builds/export.ts

<b>builds:export</b> default file path

fix: correct issue with default file path in builds:export

---

src/commands/app-credentials/list.ts

Correct description of app-credentials:list

fix: app-credentials-list desc

---

src/commands/app-configs/deploy.ts
test/commands/app-configs/deploy.test.ts

<b>app-configs:deploy</b> failed deployment error

fix: Show deployment comments in app-configs:deploy command

---

test/commands/entity-types/entity-types-test-data.ts
test/commands/entity-types/list.test.ts
test/mocks.ts

Add unit test for entity-types commands:
<b>entity-types:list</b>

test: add entity-types-list unit tests

---

test/commands/data-types/data-types-test-data.ts
test/commands/data-types/list.test.ts
test/mocks.ts

Add unit test for data-types commands:
<b>data-types:list</b>

test: add data-types-list unit tests

---

test/commands/grammars/grammars-test-data.ts
test/commands/grammars/replace.test.ts

Add unit test for <b>grammars:replace</b> command.

test: add grammars-replace unit tests

---

src/commands/applications/list.ts
src/mix/api/applications-types.ts
src/mix/api/applications.ts
src/utils/flags.ts
test/commands/applications/applications-test-data.ts
test/commands/applications/list.test.ts
test/error-handling-test-data.ts
test/error-handling.test.ts

Added filters in <b>applications:list</b> according to the new applicationsList Mix API

feat: update applications-list to newer ListApplicationsV2 endpoint

---

src/commands/locks/get.ts
test/commands/locks/get.test.ts
test/commands/locks/list.test.ts
test/commands/locks/locks-test-data.ts

Add unit test for locks commands:
<b>locks:list</b>
<b>locks:get</b>

test: add unit tests for locks commands

---

test/commands/data-hosts/data-hosts-test-data.ts
test/commands/data-hosts/latest.test.ts
test/commands/data-hosts/list.test.ts

Add unit test for data-hosts commands:
<b>data-hosts:list</b>
<b>data-hosts:latest</b>

test: add unit tests for data-hosts commands

---

src/commands/deployment-flows/list.ts

Correct use of pluralize() in deployment-flows:list

fix: correct use of pluralize() in deployment-flows:list

---

src/commands/applications/get.ts
src/mix/api/applications-types.ts
src/mix/api/applications.ts
src/mix/types.ts
test/commands/applications/applications-test-data.ts
test/commands/applications/get.test.ts

Added new command <b>applications:get</b> to get the application details.

feat: add applications:get command

---

src/utils/flags.ts

Add a closing parenthesis to buildLabelDesc.

fix: build-label description

---

src/commands/applications/list.ts
src/mix/api/applications-types.ts
src/utils/base/mix-command.ts
test/commands/applications/list.test.ts

Add support for --live-only to applications:list command

fix: add support for flag 'live-only' in applications:list

---

src/commands/app-configs/deploy.ts
src/commands/app-configs/destroy.ts
src/commands/app-configs/get.ts
src/commands/bot-interfaces/get.ts
src/commands/builds/destroy.ts
src/commands/channels/configure.ts
src/commands/channels/create.ts
src/commands/data-hosts/list.ts
src/commands/entities/configure.ts
src/commands/entities/convert.ts
src/commands/entities/create.ts
src/commands/entities/get.ts
src/commands/jobs/get.ts
src/commands/literals/import.ts
src/commands/ontology/import.ts
src/commands/projects/configure.ts
src/commands/projects/create.ts
src/commands/projects/destroy.ts
src/commands/projects/export.ts
src/commands/projects/get.ts
src/commands/samples/import.ts
src/utils/base/mix-command.ts
src/utils/errors.ts
src/utils/flags.ts
src/utils/validations.ts
test/commands/builds/list.test.ts
test/commands/grammars/replace.test.ts
test/commands/jobs/list.test.ts

Fix all the occurrences of flags being referred to with their "--' prefix.

fix: align wording around flag names

---

src/utils/flags.ts

This fixes [150](https://github.com/nuance-communications/mix-cli/issues/150).

fix: add case sensitive to with-name flag

---

src/commands/auth.ts

fix: improve suggestion on auth failure

---

package.json
src/commands/voices/list.ts
src/mix/api/voices-types.ts
src/mix/api/voices.ts
src/mix/types.ts
test/commands/voices/list.test.ts
test/commands/voices/voices-test-data.ts

Solving [#175](https://github.com/nuance-communications/mix-cli/issues/175)

feat: add voices:list command

---

README.md
package.json
src/commands/env-configs/configure.ts
src/commands/env-configs/destroy.ts
src/commands/env-configs/list.ts
src/mix/api/env-configs-types.ts
src/mix/api/env-configs.ts
src/utils/flags.ts
test/commands/env-configs/configure.test.ts
test/commands/env-configs/destroy.test.ts
test/commands/env-configs/list.test.ts

feat: add env-configs:destroy command

---

.github/workflows/test.yml
README.md
package-lock.json
package.json

Resolve vulnerabitlity by setting version of semver package to 7.5.4.
Also remove trailing period in README file, which may fix the issue we have seen with it not getting generated properly.
Resolves #193

fix: upgrade semver package

---

CHANGELOG.md
README.md

bring beta up to sync with main

chore: bring beta up to sync with main

---

package-lock.json
package.json

fix: merge beta to main

---

CHANGELOG.md

chore: merge main back to beta

---

.github/workflows/test.yml
package-lock.json
package.json

This PR is to upgrade async and axios to address vulnerabilities.

fix: upgrade async and axios
